name: "my_recipe_book"
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  firebase_core_web: any
  provider: ^6.1.1 
  uuid: ^4.4.0 
  cloud_firestore: ^4.8.3



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/log.png"
  
flutter:

  uses-material-design: true
  assets:
    - assets/LOGO.png
    - assets/mare.jpg
    - assets/orient.jpg
    - assets/login_bg.jpg
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab.ttf
          weight: 700



